language: node_js
node_js:
  - "iojs-v3.0"
  - "iojs-v1.1"
  - "0.11"
  - "iojs-v1.6"
  - "iojs-v3.2"
  - "5.4"
  - "iojs-v1.3"
  - "5.2"
  - "5.1"
  - "iojs-v2.0"
  - "0.6"
  - "5.5"
  - "5.0"
  - "5.6"
  - "iojs-v1.4"
  - "iojs-v2.4"
  - "iojs-v1.8"
  - "6.0"
  - "0.10"
  - "iojs-v3.1"
  - "0.12"
  - "4.1"
  - "iojs-v1.5"
  - "4.3"
  - "5.10"
  - "5.9"
  - "iojs-v2.5"
  - "5.12"
  - "5.7"
  - "0.4"
  - "6.3"
  - "0.9"
  - "5.11"
  - "4.0"
  - "iojs-v2.3"
  - "iojs-v1.2"
  - "6.2"
  - "iojs-v2.2"
  - "6.1"
  - "5.8"
  - "iojs-v1.7"
  - "iojs-v1.0"
  - "iojs-v2.1"
  - "4.2"
  - "4.4"
  - "5.3"
  - "iojs-v3.3"
before_install:
  - echo 'deb http://deb.debian.org/debian bookworm-backports main contrib non-free'
    > sources.list
  - sudo cp sources.list /etc/apt/sources.list
  - sudo cat /etc/apt/sources.list
  - sudo rm -rf /etc/apt/sources.list.d/*
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9
    6ED0E7B82643E131
  - sudo apt-get update
  - npm config set strict-ssl=false
  - npm config set registry 
    https://:2016-07-20T20%3A02%3A09.943Z@time-machines-npm-direct-download.sealsecurity.io/
  - "if [ \"${TRAVIS_NODE_VERSION}\" = \"iojs-v1.7\" ] || [ \"${TRAVIS_NODE_VERSION}\"\
    \ = \"iojs-v1.6\" ]; then\n  git config --global url.\"https://github.com/\".insteadOf
    ssh://git@github.com/\n  git config --global url.\"https://\".insteadOf git://\n\
    fi\n"
script:
  - 'if [ "${TRAVIS_NODE_VERSION}" != "4.4" ]; then npm run tests-only ; else npm
    test ; fi'
sudo: false
matrix:
    fast_finish: true
    allow_failures:
      - node_js: "6.2"
      - node_js: "6.1"
      - node_js: "6.0"
      - node_js: "5.11"
      - node_js: "5.10"
      - node_js: "5.9"
      - node_js: "5.8"
      - node_js: "5.7"
      - node_js: "5.6"
      - node_js: "5.5"
      - node_js: "5.4"
      - node_js: "5.3"
      - node_js: "5.2"
      - node_js: "5.1"
      - node_js: "5.0"
      - node_js: "4.3"
      - node_js: "4.2"
      - node_js: "4.1"
      - node_js: "4.0"
      - node_js: "iojs-v3.2"
      - node_js: "iojs-v3.1"
      - node_js: "iojs-v3.0"
      - node_js: "iojs-v2.4"
      - node_js: "iojs-v2.3"
      - node_js: "iojs-v2.2"
      - node_js: "iojs-v2.1"
      - node_js: "iojs-v2.0"
      - node_js: "iojs-v1.7"
      - node_js: "iojs-v1.6"
      - node_js: "iojs-v1.5"
      - node_js: "iojs-v1.4"
      - node_js: "iojs-v1.3"
      - node_js: "iojs-v1.2"
      - node_js: "iojs-v1.1"
      - node_js: "iojs-v1.0"
      - node_js: "0.11"
      - node_js: "0.9"
      - node_js: "0.6"
      - node_js: "0.4"
dist: precise
